stages:
  - build
  - deploy

variables:
  REGISTRY_HOST: "100.80.234.21:30500"
  REGISTRY_USER: "rigbyadmin"
  REGISTRY_PASSWORD: "gKofUm6xLSHP1x5x1REZXFHl"
  IMAGE: "100.80.234.21:30500/rigbyhost/nitrocore"

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${REGISTRY_HOST}\":{\"username\":\"${REGISTRY_USER}\",\"password\":\"${REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context dir://. --dockerfile Dockerfile --destination ${IMAGE}:${CI_COMMIT_SHA} --destination ${IMAGE}:latest --insecure --insecure-registry ${REGISTRY_HOST}

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -f k8s/
    - kubectl rollout restart deployment/nitrocore -n rigby-host
  only:
    - main
    - master
