stages:
  - build
  - deploy

variables:
  REGISTRY_HOST: "100.80.234.21:30500"
  REGISTRY_USER: "rigbyadmin"
  REGISTRY_PASSWORD: "gKofUm6xLSHP1x5x1REZXFHl"
  IMAGE: "100.80.234.21:30500/rigbyhost/nitrocore"
  DOCKER_OPTS: "--insecure-registry 100.80.234.21:30500"

default:
  before_script:
    - mkdir -p /etc/docker && echo "{\"insecure-registries\":[\"100.80.234.21:30500\"]}" > /etc/docker/daemon.json

build:
  stage: build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      command: ["--insecure-registry=100.80.234.21:30500"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "${REGISTRY_PASSWORD}" | docker login ${REGISTRY_HOST} -u "${REGISTRY_USER}" --password-stdin
    - docker build -t ${IMAGE}:${CI_COMMIT_SHA} -t ${IMAGE}:latest .
    - docker push ${IMAGE}:${CI_COMMIT_SHA}
    - docker push ${IMAGE}:latest

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script: []
  script:
    - kubectl apply -f k8s/
    - kubectl rollout restart deployment/nitrocore -n rigby-host
  only:
    - main
    - master
