/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterAll: typeof import('vitest')['afterAll']
  const afterEach: typeof import('vitest')['afterEach']
  const assert: typeof import('vitest')['assert']
  const beforeAll: typeof import('vitest')['beforeAll']
  const beforeEach: typeof import('vitest')['beforeEach']
  const chai: typeof import('vitest')['chai']
  const defaultConfig: typeof import('../server/utils/useDrizzle')['defaultConfig']
  const defineNitroConfig: typeof import('nitropack/config')['defineNitroConfig']
  const describe: typeof import('vitest')['describe']
  const expect: typeof import('vitest')['expect']
  const it: typeof import('vitest')['it']
  const makeCommitable: typeof import('../server/utils/useCommit')['makeCommitable']
  const setupCommitListener: typeof import('../server/utils/useCommitFabric')['setupCommitListener']
  const suite: typeof import('vitest')['suite']
  const test: typeof import('vitest')['test']
  const useCommit: typeof import('../server/utils/useCommit')['useCommit']
  const useCommitFabric: typeof import('../server/utils/useCommitFabric')['useCommitFabric']
  const useCommitMiddleware: typeof import('../server/utils/useCommit')['useCommitMiddleware']
  const useCrypto: typeof import('../server/utils/useCrypto')['useCrypto']
  const useDrizzle: typeof import('../server/utils/useDrizzle')['useDrizzle']
  const useDrizzlePoolManager: typeof import('../server/utils/useDrizzle')['useDrizzlePoolManager']
  const useFabric: typeof import('../server/utils/useFabric')['useFabric']
  const useGeometryDashTooling: typeof import('../server/utils/useGeometryDashTooling')['useGeometryDashTooling']
  const useGzip: typeof import('../server/utils/useGzip')['useGzip']
  const usePerformance: typeof import('../server/utils/usePerformance')['usePerformance']
  const usePostObject: typeof import('../server/utils/usePostObject')['usePostObject']
  const useServerConfig: typeof import('../server/utils/useServerConfig')['useServerConfig']
  const useStorage: typeof import('./mocks/useStorage')['useStorage']
  const useTemporalFabric: typeof import('../server/utils/useFabric')['useTemporalFabric']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Maybe, Nullable, MaybeUndefined, MakeOptional } from '../server/utils/types'
  import('../server/utils/types')
  // @ts-ignore
  export type { Database } from '../server/utils/useDrizzle'
  import('../server/utils/useDrizzle')
}
