# For standalone mode
services:
    app:
      build:
        context: ..
        dockerfile: ../Dockerfile
      scale: 1
      environment:
        - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      volumes:
        - ./savedata:/savedata
        - ./config.json:/config/0000
      restart: unless-stopped
      depends_on:
        - postgres

    postgres:
      image: postgres:17
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
      volumes:
        - postgres:/var/lib/postgresql/data
      restart: unless-stopped

    adminer:
      image: adminer
      restart: unless-stopped
      depends_on:
        - postgres

    caddy:
      image: caddy
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
        - "443:443/udp"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
      depends_on:
        - app
        - adminer

volumes:
  - caddy_data:
  - caddy_config:
  - postgres:
