apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nitrocore-redirect
  namespace: rigby-host
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      return 308 https://gdps.rigbyhost.com$request_uri;
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - gdps.rigby.host
    secretName: gdps-rigby-host-tls
  rules:
  - host: gdps.rigby.host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nitrocore
            port:
              number: 3000
